import SwaggerJSDoc from 'swagger-jsdoc';

const options = {
  swaggerDefinition: {
    openapi: '3.0.3',
    info: {
      title: 'Documentation Swagger node-boilerplate',
      version: '1.0.0',
      description: 'A boilerplate for Node.js',
      license: {
        name: 'MIT',
        url: 'https://choosealicense.com/licenses/mit/',
      },
      contact: {
        name: 'Christophe Parmentier',
        email: 'cparmentier.dev@gmail.com',
      },
    },
    host: 'localhost:8081',
    basePath: '/api',
    components: {
      securitySchemes: {
        ApiKeyAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          in: 'header',
          name: 'APIToken',
          description: `For accessing the API a valid JWT token must be passed in
the 'Authorization' header.

A valid JWT token is generated by the API and retourned as answer of a call
to the route /login giving a valid email & password.

The following syntax must be used in the 'Authorization' header :

Bearer: xxxxxx.yyyyyyy.zzzzzz`,
        },
      },
    },
    servers: [
      {
        url: 'http://localhost:8081/api/',
      },
    ],
  },
  basePath: '/',
  apis: ['./server/modules/*/router.js', './database/models/*.js'],
};

export default SwaggerJSDoc(options);
